### PR TITLE
Updated Scheduler feature to support persistence

### PR DESCRIPTION
**Pull request by miroslav-beranic**
Updated import packages resolution.

- ScheduleOptions was made Serializable, with addition to move Trigger creation from InternalScheduleOptions's constructor to method compile().
- getJobs() method from Scheduler interface returns String names and not Objects
- Added custom StdScheduler and StdSchedulerFactory classes, to implemented changes
- Added SchedulerStorage as support for "backward compatibility" and "short lived" jobs. This is not good place to use it.
- Updated QuartzJobExecutor to remove non-serializable items from JobDataMap storage
- Updated Scheduler Shell commands to use changed Scheduler API ( job names are as keys )

### CODE REVIEW

**Comment by miroslav-beranic** [comment]
I am looking into why build failed. Was able to build it local.

**Comment by jbonofre** [comment]
@miroslav-beranic it's not related to your PR. Build is failing on `master`. I'm fixing. You will just have to rebase. I will explain to you how to do that if you want.

**Comment by jbonofre** [comment]
Can you please rebase (I fixed the build with #606 ) ?

**Comment by miroslav-beranic** [comment]
Hi JB, I will drop this one. I've decided to go slow and will make more branches and smaller changes. I did quite a mess inside Scheduler :/ Will close this one.

**Pull request closed without merging**
