### PR TITLE
#KARAF-5632: Reuse in HeapDumpProvider now the copy function of LogDu…

### PR DESCRIPTION
**Pull request by rhierlmeier**
Fixed the copy of the dumpfile in the HeapDumpProvider

### CODE REVIEW

**Comment by gnodet** [comment]
retest this please

**Comment by gnodet** [comment]
retest this please

**Comment by jbonofre** [comment]
This PR should have been based on `master` instead of `karaf-3.0.x`. I'm  testing the branch locally. I think same fix can be applied on other branches no ?

**Comment by rhierlmeier** [comment]
in karaf-4.0.x, karaf-4.1.x and master the HeadDumbProvider is correctly implemented.

**Comment by jbonofre** [comment]
@rhierlmeier thanks for the update. Let me test the PR locally before merging and cutting 3.0.9.

**Comment by jbonofre** [comment]
By the way, this PR will never build as the Jenkins  PR uses JDK 8 whereas karaf 3.0.x is supposed to be built with 1.7, that's why I'm testing locally.

**Comment by jbonofre** [comment]
It has been merged.

**Pull request closed without merging**
