### PR TITLE
KARAF-7726 - Upgrade to org.osgi.service.jdbc 1.1.0, Pax Transx 0.5.4, Pax JDBC 1.5.6

### PR DESCRIPTION
**Pull request by jbonofre**

### CODE REVIEW

**Review by oscerd — APPROVED** [review]

**Comment by jbonofre** [comment]
It should be aligned with `pax-jdbc`.

**Review by grgrzybek — APPROVED** [review]
Pax JMS 1.1.3 coming today!

**Comment by jbonofre** [comment]
@grgrzybek no problem. By the way, it seems pax-jdbc 1.5.6 artifacts are not yet available on Maven Central.

**Comment by grgrzybek** [comment]
Pax Transx 0.5.4 and Pax JDBC 1.5.6 were added just few hours ago.
I'm finishing Pax JMS 1.1.3 now.

**Pull request merged**
