### PR TITLE
Typo in KarafTestSupport

### PR DESCRIPTION
**Pull request by oltruong**
Typo in getAvailablePort calling for rmiRegistryPort: the second argument should be the MAX_RMI_REG_PORT, not the MIN_RMI_REG_PORT.

### CODE REVIEW

**Comment by jbonofre** [comment]
R: @jbonofre

**Comment by jbonofre** [comment]
For the record, please open a pull request only on master: it's the only branch monitored by the github integration.

**Comment by oltruong** [comment]
I understand but the problem was that the issue was not on the main branch. Anyway thanks for fixing it.

**Comment by jbonofre** [comment]
No worries, I did an empty commit on master to automatically close the PR. For issue on a specific branch, please, create a Jira first attaching a patch. Thanks !

**Pull request closed without merging**
