### PR TITLE
[KARAF-5208] Improve feature:install error message

### PR DESCRIPTION
**Pull request by jludvice**
R: @jbonofre

### CODE REVIEW

**Comment by jbonofre** [comment]
Thanks ! I'm reviewing.

**Comment by gnodet** [comment]
Shouldn't we override ```getMessage()``` instead ?
Something like:
```
public String getMessage() {
            StringBuilder sb = new StringBuilder(super.getMessage());
            sb.append(":");
            for (Exception e : exceptions) {
                sb.append("\n\t");
                sb.append(e.getMessage());
            }
}
```

**Comment by jludvice** [comment]
On which class @gnodet ?

**Comment by gnodet** [comment]
On ```MultiException```.  It should then print the root causes, even if the full stack is not printed.

**Comment by jludvice** [comment]
This also works for me.
```
karaf@root()> feature:install spring-jdbc                                                                                                                               15:13:00
Error executing command: Error:
        Error downloading mvn:org.apache.servicemix.bundles/org.apache.servicemix.bundles.spring-jdbc/4.3.7.RELEASE_1
```

compared to previous
```
karaf@root()> feature:install spring-jdbc
Error executing command: Error downloading mvn:org.apache.servicemix.bundles/org.apache.servicemix.bundles.spring-tx/4.3.7.RELEASE_1
```

@gnodet's solution looks less hackish.
Are we going to prefer overriding `getMessage`?

**Comment by jbonofre** [comment]
Personally, I don't mind: either way is fine to me.

**Comment by jludvice** [comment]
Just from curiosity, why is this class implemented three times in karaf?
* https://github.com/apache/karaf/blob/master/features/core/src/main/java/org/apache/karaf/features/internal/util/MultiException.java
* https://github.com/apache/karaf/blob/master/shell/console/src/main/java/org/apache/karaf/shell/console/MultiException.java
* https://github.com/apache/karaf/blob/master/shell/core/src/main/java/org/apache/karaf/shell/support/MultiException.java

Wouldn't it make sense to have just one where we include this fix?

**Comment by gnodet** [comment]
Overriding the ```getMessage``` has the benefit of displaying all the inner exceptions in case there are more than one problem.  The previous solution only displays the first one.

**Comment by jbonofre** [comment]
@gnodet that makes sense. @jludvice can you please update accordingly ?

**Comment by jbonofre** [comment]
retest this please

**Comment by jludvice** [comment]
retest this please

**Comment by jbonofre** [comment]
retest this please

**Comment by jbonofre** [comment]
I updated Jenkins config to be able to trigger pull request build.

**Pull request closed without merging**
