### PR TITLE
[KARAF-7367] add Reproducible Builds support

### PR DESCRIPTION
**Pull request by hboutemy**
see https://issues.apache.org/jira/browse/KARAF-7367

### CODE REVIEW

**Review by oscerd — APPROVED** [review]

**Review by skitt — APPROVED** [review]

**Comment by skitt** [comment]
Rat is complaining.

**Comment by hboutemy** [comment]
given no file was added in this commit, I don't see what it can change at Rat level
and the output of the failing build is not really helping

**Comment by jbonofre** [comment]
I suspect it's the test using MavenArchiver that doesn't output in the right target directory. I gonna take a look.

**Comment by jbonofre** [comment]
This change causes the following error:

```
[ERROR] Failed to execute goal org.apache.karaf.tooling:karaf-maven-plugin:4.4.0-SNAPSHOT:kar (package) on project framework: Execution package of goal org.apache.karaf.tooling:karaf-maven-plugin:4.4.0-SNAPSHOT:kar failed: An API incompatibility was encountered while executing org.apache.karaf.tooling:karaf-maven-plugin:4.4.0-SNAPSHOT:kar: java.lang.NoSuchMethodError: org.codehaus.plexus.util.DirectoryScanner.setFilenameComparator(Ljava/util/Comparator;)V
```

I think the problem is related to maven/plexus dep update. I will take a look.

**Comment by hboutemy** [comment]
oh, you need to update plexus-utils to a recent release: resolution seems to prefer an older version than required by maven-archiver

**Comment by hboutemy** [comment]
strangely, I tested ITs, so I don't get how you got such result while everything runs fine for me...

**Comment by hboutemy** [comment]
you'll need to update `plexus-utils.version` property to 3.3.0 minimum (currently 3.2.1) to benefit from https://github.com/codehaus-plexus/plexus-utils/issues/70

**Pull request merged**
