### PR TITLE
KARAF-4672: Make karaf.shutdown.pid.file active by default

### PR DESCRIPTION
**Pull request by lburgazzoli**

### CODE REVIEW

**Comment by jbonofre** [comment]
Is there no overldap with #231 ?

**Comment by lburgazzoli** [comment]
This is a PR against karaf-4.0.x 

As per jira note, I've opened two PRs to cope with:
- 4.1.x -> rename karaf.shutdown.pid.file to karaf.pid.file + backward compatibility
- 4.0.x -> make karaf.shutdown.pid.file active by default

But I can rework them

**Comment by jbonofre** [comment]
Please, just provide PR on master (and I will cherry-pick/merge on karaf-4.0.x branch). The reason is that github will automatically close the PR when merged only on master. Thanks !

**Comment by jbonofre** [comment]
So, basically, please, close this one, and we will deal with #231 only.

**Comment by lburgazzoli** [comment]
perfect :-)

**Pull request closed without merging**
