### PR TITLE
[KARAF-5722] Upgrade to ASM 6.2 and Aries Proxy Impl 1.1.2

### PR DESCRIPTION
**Pull request by jbonofre**

### CODE REVIEW

**Comment by jbonofre** [comment]
retest this please

**Comment by jbonofre** [comment]
retest this please

**Comment by jbonofre** [comment]
Aries Proxy should be updated. I'm tackling that.

**Comment by ffang** [comment]
Hi @jbonofre 
FYI, I have two patch for Aries proxy-impl which can enable it to work with java10 and ASM 6.1.1
They are
https://issues.apache.org/jira/browse/ARIES-1796
https://issues.apache.org/jira/browse/ARIES-1797

Could you please review and apply those patches?

Thanks
Freeman

**Comment by jbonofre** [comment]
I'm preparing the Aries Proxy Impl 1.1.2 release.

**Comment by jbonofre** [comment]
Aries Proxy Impl 1.1.2 is on vote.

**Comment by jbonofre** [comment]
retest this please

**Pull request merged**
