### PR TITLE
KARAF-5421 - add user friendly error when installing non OSGi bundle …

### PR DESCRIPTION
**Pull request by awrb**
…via bundle:install

### CODE REVIEW

**Comment by jbonofre** [comment]
Did you check if you directly install a blueprint xml ? The blueprint xml doesn't contain manifest so I think your change will block it.

**Comment by awrb** [comment]
Good point @jbonofre, I will check in the evening. If it doesn't work then I'll add a test since the current ones did not detect it if it broke. Although the previous code looks like it wouldn't work too, because it was either manifest version == "2" or exception (unless --r3-bundles is passed).

**Comment by jbonofre** [comment]
Yes I think blueprint installer is creating a bundle on the fly. So that's why it works.

**Comment by awrb** [comment]
> Yes I think blueprint installer is creating a bundle on the fly. So that's why it works.

The docs say it does https://karaf.apache.org/manual/latest/#_blueprint_deployer
```
The generated OSGi MANIFEST will contain the following headers:

Manifest-Version: 2
Bundle-SymbolicName: [name of the file]
Bundle-Version: [version of the file]
Import-Package: [required packages]
DynamicImport-Package: *
```
but I am not sure when this happens compared to bundle:install.

**Comment by awrb** [comment]
@jbonofre I just tried manually and it looks like the blueprint bundles install fine, e.g. the bundles of mvn:org.apache.karaf.examples/karaf-blueprint-example-* (as confirmed by karaf/itests/test/src/test/java/org/apache/karaf/itests/examples/BlueprintExampleTest.java passing in the pipeline).

But they are already bundles because of `<packaging>bundle</packaging>` and `maven-bundle-plugin`. Blueprint just handles service dynamics. Am I missing something?

**Comment by jbonofre** [comment]
@awrb that's blueprint bundles, I mean that it's possible to directly deploy blueprint XML in Karaf:

```
bundle:install blueprint:mvn:...
```

I will test myself later today or tomorrow.

**Comment by awrb** [comment]
image
after `bundle:install -s blueprint:file:...` it generates Bundle-ManifestVersion automatically for me. But I'm just testing one use case so if you can test too that's great.

**Review by jbonofre — APPROVED** [review]

**Pull request merged**
