### PR TITLE
KARAF-7098 JsonConfigInstaller ignores R7 factory configurations

### PR DESCRIPTION
**Pull request by oliverlietz**

### CODE REVIEW

**Comment by jbonofre** [comment]
It seems that this PR includes #1346. It would be great to gather both in the same PR (unique PR), or link both together. Anyway two not related commits are not easy to review.

**Review by jbonofre — CHANGES_REQUESTED** [review]
The PR and config bundle is not good. It should use `org.apache.karaf.util.config` as private package, else we have the following issue:

```
Message: Unable to resolve root: missing requirement [root] osgi.identity; osgi.identity=minimal; type=karaf.feature; version=4.3.2.SNAPSHOT; filter:="(&(osgi.identity=minimal)(type=karaf.feature)(version>=4.3.2.SNAPSHOT))" [caused by: Unable to resolve minimal/4.3.2.SNAPSHOT: missing requirement [minimal/4.3.2.SNAPSHOT] osgi.identity; osgi.identity=config; type=karaf.feature [caused by: Unable to resolve config/4.3.2.SNAPSHOT: missing requirement [config/4.3.2.SNAPSHOT] osgi.identity; osgi.identity=org.apache.karaf.config.core; type=osgi.bundle; version="[4.3.2.SNAPSHOT,4.3.2.SNAPSHOT]"; resolution:=mandatory [caused by: Unable to resolve org.apache.karaf.config.core/4.3.2.SNAPSHOT: missing requirement [org.apache.karaf.config.core/4.3.2.SNAPSHOT] osgi.wiring.package; filter:="(osgi.wiring.package=org.apache.karaf.util.config)"]]]
```

**Comment by oliverlietz** [comment]
I see, so embedding via e.g. `org.apache.karaf.util.config;-split-package:=merge-first,` is the preferred way, right?

**Comment by jbonofre** [comment]
Yes, like the other util packages. But don't worry, I'm fixing that. Thanks !

**Comment by jbonofre** [comment]
Superseeded by PR #1369

**Pull request closed without merging**
