### PR TITLE
Ensure jre and eecap config.properties properties can be computed for modern jvms

### PR DESCRIPTION
**Pull request by rmannibucau**
Mainly to show how to not have to update properties each 6 months (see #1723 for context)

### CODE REVIEW

**Review by fpapon — APPROVED** [review]
LGTM
Thanks!

**Comment by jbonofre** [comment]
NB: the PR doesn't prevent the update in `etc/jre.properties` but help to deal with ee caps.

**Comment by mattrpav** [comment]
@rmannibucau shouldn't the eecap-* entries the be able to be removed from the etc/config.properties? 

This approach looks way better!

**Comment by rmannibucau** [comment]
@mattrpav the eecap and jre props defaulting to a previous value (or just appending their number) can be removed until java 9 (to keep). One option which is not bad is to decide to define all LTS and skip others, this enables to not loop too much but also to work most of the time without any explicit config so think it can be a wise compromise.

**Comment by jbonofre** [comment]
@mattrpav we can't remove the old entries for some version of JDKs. However it's possible for Karaf 4.5.x.

**Comment by jbonofre** [comment]
I'm testing/reviewing this PR. Thanks !

**Review by jbonofre — APPROVED** [review]

**Pull request merged**
