### PR TITLE
[KARAF-3879] jdbc feature should installs pax-jdbc feature

### PR DESCRIPTION
**Pull request by oscerd**
Hi all,

This PR is related to:
https://issues.apache.org/jira/browse/KARAF-3879

Andrea

### CODE REVIEW

**Comment by oscerd** [comment]
Rebased

**Comment by jbonofre** [comment]
Quick question: what's the command you used for the rebase ?

**Comment by oscerd** [comment]
Git pull --rebase upstream master

I think actually is behind the latest commit.. I've rebased two or three
days ago
Il 05/nov/2015 07:47, "Jean-Baptiste Onofré" <notifications@github.com> ha
scritto:

**Comment by oscerd** [comment]
If there are troubles I can submit a new PR :-)
Il 05/nov/2015 07:48, "Andrea Cosentino" <ancosen@gmail.com> ha scritto:

**Comment by jbonofre** [comment]
No problem, just wondering. I'm pulling now.

**Pull request merged**
