### PR TITLE
[KARAF-6684] Upgrade to felix webconsole 4.5.0

### PR DESCRIPTION
**Pull request by jbonofre**

### CODE REVIEW

**Comment by oliverlietz** [comment]
@jbonofre The upgrade is incomplete, please also adjust the API version (exported package):
```
        <felix.webconsole.version>4.4.0</felix.webconsole.version>
        <felix.webconsole.api.version>3.3.0</felix.webconsole.api.version>
```

**Comment by jbonofre** [comment]
It's done already, forgot to push the right commit.

**Comment by jbonofre** [comment]
As vote is done, I'm upgrading to WebConsole 4.5.0.

**Comment by jbonofre** [comment]
retest this please

**Pull request merged**
