### PR TITLE
[KARAF-7032] Provide a test for JTA API and change javax.transaction.…

### PR DESCRIPTION
**Pull request by grgrzybek**
…* configuration in jre.properties and config.properties

### CODE REVIEW

**Review by oscerd — APPROVED** [review]

**Comment by jbonofre** [comment]
@grgrzybek FYI, I created https://github.com/apache/karaf/pull/1316 to fix the `karaf-4.2.x` build on Jenkins.

**Comment by grgrzybek** [comment]
> @grgrzybek FYI, I created #1316 to fix the `karaf-4.2.x` build on Jenkins.

Thanks!

**Comment by jbonofre** [comment]
@grgrzybek can you please rebase on `karaf-4.2.x` to see if Jenkins is happy ;)

**Comment by grgrzybek** [comment]
rabased, waiting...

**Pull request merged**
