### PR TITLE
[KARAF-7879] Use pax-web-8.0.28

### PR DESCRIPTION
**Pull request by holgerfriedrich**
Upgrade to Jetty from 9.4.54 to 9.4.56.v20240826
Upgrade to commons-codec from 1.15 to 1.17.0

### CODE REVIEW

**Comment by jbonofre** [comment]
It's incomplete as I'm preparing new pax web release. I close this one in favor of the one I will create.

**Comment by grgrzybek** [comment]
> It's incomplete as I'm preparing new pax web release. I close this one in favor of the one I will create.

What Pax Web version do you want? I've already updated Jetty to `9.4.56.v20240826`, but didn't release yet. I can do it (after I update to Tomcat 9.0.96 too) during weekend, ok?

**Comment by jbonofre** [comment]
I plan couple of other updates (asm, etc)

**Comment by jbonofre** [comment]
Jetty is updated but not yet released in pax web.

**Comment by grgrzybek** [comment]
I'm just testing 8.0.x branch with additional Tomcat and Undertow updates.

**Comment by jbonofre** [comment]
I can also do a pass in other dependencies and release. Up to you.

**Comment by grgrzybek** [comment]
Tests are finishing, I'll check what else could be updated, but runtimes (jetty, tomcat, undertow) are enough for new release.

**Pull request closed without merging**
