### PR TITLE
KARAF-6661: Add javax.activation to jre9

### PR DESCRIPTION
**Pull request by graben**

### CODE REVIEW

**Comment by ffang** [comment]
Please don't merge, we have some reasons to do it
https://issues.apache.org/jira/browse/KARAF-4154

**Comment by graben** [comment]
@ffang : Does this mean the javax.activation-1.2.0.jar under lib/jdk9plus is wrong?

**Comment by ffang** [comment]
Hi @graben ,

No, it's not wrong, IIRC it's on the classpath so it's still be used to launch the OSGi container at early stage, when OSGi classloading(bundle export) mechanism not kick in yet.

You should install activation bundle yourself to use it.

Best Regards
Freeman

**Comment by graben** [comment]
So it's needed to be bundled twice.

**Comment by jbonofre** [comment]
Related to that, you can see the message I sent on the mailing list couple of weeks ago: `jdk9plus` should be removed and we should preferably use spec bundles.

**Pull request closed without merging**
