### PR TITLE
KARAF-6698 VerifyMojo performance improvement

### PR DESCRIPTION
**Pull request by he2**

### CODE REVIEW

**Comment by jbonofre** [comment]
retest this please

**Comment by jbonofre** [comment]
retest this please

**Comment by he2** [comment]
The failing test in Jenkins reported:
`
java.lang.ClassNotFoundException: org.apache.derby.iapi.error.StandardException (no security manager: RMI class loader disabled)
`

That is a strange failure considering what I have changed. Could it be something else ?
I re-ran the build on my local using : mvn clean verify -Prat

It fails with a different error:
`ExternalConfigTest: externalConfigTest
2020-05-17 23:45:04,843 | INFO  | exam.spi.reactors.ReactorManager  444 | suite finished
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 7.473 s - in org.apache.karaf.itests.ExternalConfigTest
[INFO] 
[INFO] Results:
[INFO] 
[ERROR] Errors: 
[ERROR]   SoapExampleTest.testBlueprint » WebService Could not find wsdl:binding operati...`

Please let me know if I'm making a mistake somewhere.

Thanks.

**Comment by he2** [comment]
Never mind my previous comment, I see it was merged. Thanks.

**Pull request merged**
