### PR TITLE
[KARAF-6430] - Considering all features in a feature including the features defined …

### PR DESCRIPTION
**Pull request by ricardosilva88**
…inside conditionals

Continuation of https://github.com/apache/karaf/pull/880, but this time aiming to merge into master

### CODE REVIEW

**Comment by jbonofre** [comment]
Your change is not fully correct as the conditional feature might not have a version, and the resolution will fail.

**Comment by ricardosilva88** [comment]
@jbonofre I don't see how this can happens. In our validation example, we don't indicate any feature version - https://paste.ofcode.org/UjVKQENQCYDFrKFTwgARgX and it resolves the feature.

Can you please indicate a scenario where this can happen? So we can validated that. Ty

**Comment by ricardosilva88** [comment]
@jbonofre , can you please answer my question on latest comment? Ty

**Comment by ricardosilva88** [comment]
@jbonofre any update on this PR? Is missing something from my side?

**Comment by jbonofre** [comment]
@ricardosilva88 oops sorry I forgot your PR. Let me resume the review on it, but when I tested it breaks the resolution. Let me resume the review.

**Comment by jbonofre** [comment]
retest this please

**Comment by ricardosilva88** [comment]
Noticed that are some examples failing due to this change, I will be working to fix and probably adding some tests

**Comment by ricardosilva88** [comment]
@jbonofre just pushed my fix's for the tests that were failing

**Comment by jbonofre** [comment]
retest this please

**Comment by jbonofre** [comment]
retest this please

**Comment by jbonofre** [comment]
retest this please

**Comment by ricardosilva88** [comment]
@jbonofre I already rebase against master and on my local machine it does work. I don't see any valid reason or log on your Jenkins for this failure.

**Comment by ricardosilva88** [comment]
retest this please

**Comment by ricardosilva88** [comment]
"ERROR: Maven Home /home/jenkins/tools/maven/apache-maven-3.6.0 doesnt exist"

**Comment by jbonofre** [comment]
@ricardosilva88 yes, I'm fixing that. It's related to a change we did on Jenkins executors.

**Comment by jbonofre** [comment]
Jenkins configuration has been updated.

**Comment by jbonofre** [comment]
retest this please

**Comment by jbonofre** [comment]
retest this please

**Comment by jbonofre** [comment]
retest this please

**Comment by jbonofre** [comment]
retest this please

**Pull request closed without merging**
