### PR TITLE
upgraded Felix SCR to 2.0.6 and SCR compat to 1.0.4

### PR DESCRIPTION
**Pull request by CodingFabian**
as discussed on the mailing list, i propose to include the scr upgrade in karaf 4.0.x

### CODE REVIEW

**Comment by jbonofre** [comment]
I did it already on a local branch.

See: https://issues.apache.org/jira/browse/KARAF-4616

**Comment by CodingFabian** [comment]
Issue says 2.0.4. But that is broken

**Comment by jbonofre** [comment]
Oh thanks ! Fixing that.

**Comment by jbonofre** [comment]
R: @jbonofre

**Pull request closed without merging**
