### PR TITLE
Propose docker run commands with clean up tag in manual

### PR DESCRIPTION
**Pull request by essobedo**
## Motivation

When working with Docker it is important to ensure that once over everything is properly cleaned up otherwise it quickly gets space consuming

## Modification

* Add the clean up flag to the docker run commands in the manual

### CODE REVIEW

**Comment by jbonofre** [comment]
Not sure it makes such sense like this. Maybe just mentioning the option is enough.

**Comment by essobedo** [comment]
Do you mean that you intentionally want to keep the container? For debugging purpose or to reuse it later? If you prefer to keep it maybe docker stop or Ctrl + C (as foreground mode is used here) are less risky than docker kill, don't you agree? And maybe a section to explain how to re-start the container could be added WDYT? Or if you rather prefer to keep it as it is, I understand, let's close it, it is only a small remark I had while reading the very nice and clear manual of the project, congrats for it BTW.
Let me know what you prefer?

**Comment by jbonofre** [comment]
Yes it's intentional. For instance, a classic use case is to start a container, do some stuff on it and then stop it and tag to create an image. 

So imho it's better to keep the container by default. If the user really wants to remove it after run then he can do it on his own.

**Comment by essobedo** [comment]
I see, so let's close it then, sorry for the noise

**Pull request closed without merging**
