### PR TITLE
[KARAF-5906] Update to Apache Felix Webconsole 4.3.8

### PR DESCRIPTION
**Pull request by fpapon**
Update to Apache Felix Webconsole 4.3.8 and latest jQuery UI 1.12.1.

I also made some changes on the CSS nav menu.

### CODE REVIEW

**Comment by jbonofre** [comment]
retest this please

**Comment by jbonofre** [comment]
retest this please

**Comment by fpapon** [comment]
The rationale for the css is that there was a border and a background around every sub-items of the top nav menu. I just remove the border and make the background transparent.

**Comment by jbonofre** [comment]
retest this please

**Pull request merged**
