### PR TITLE
[KARAF-5627] Upgrade to PAX-JMS 0.2.0

### PR DESCRIPTION
**Pull request by gnodet**

### CODE REVIEW

**Comment by jbonofre** [comment]
retest this please

**Comment by jbonofre** [comment]
retest this please

**Comment by jbonofre** [comment]
retest this please

**Comment by jbonofre** [comment]
retest this please

**Comment by johnpoth** [comment]
retest this please

**Comment by jbonofre** [comment]
retest this please

**Comment by gnodet** [comment]
The Pax-JMS 0.2.0 features actually have some problems because a library required at runtime is not installed.  That's because a package is flagged optional (and should be) but the code has mandatory requirements on it right now (easy to break).  For those reasons, we should defer the upgrade until a new release comes up with a fix.

**Comment by jbonofre** [comment]
+1, thanks for the update. It's also good to test the update using PR with Jenkins build ;)

**Pull request closed without merging**
