### PR TITLE
[KARAF-5432] Upgrade to Felix Utils 1.10.4 and FileInstall 3.6.4

### PR DESCRIPTION
**Pull request by gnodet**
[KARAF-5313] Exception when deleting a .cfg file from hot deploy directory

### CODE REVIEW

**Comment by jbonofre** [comment]
retest this please

**Comment by jbonofre** [comment]
Full build passed without problem on my box. I did tests with `config:*` commands. Almost ok, but when I did:

```
config:edit net.test
config:property-set foo bar
```

The configuration is OK (I can see it with `config:list (service.pid=net.test)`. However, the `net.test.cfg` is not created in the `etc` folder, whereas it should. It's regression for me and has to be fixed.

**Comment by jbonofre** [comment]
Hmmm, it's not related directly to the PR as on `master`, the file is not created neither (whereas it works fine on 4.1.x). I wonder if it doesn't make sense to "re-add" the `cfg` file creation.

**Comment by gnodet** [comment]
Yes, it makes sense, let me fix the cfg problem.  I don't think we need to write it explicitely, we just need to add the filename entry to point to the etc directory and fileinstall will write it to disk.

**Comment by jbonofre** [comment]
Thanks ! Yeah, just adding the `felix.filename` config property should do the trick ;)

**Comment by jbonofre** [comment]
Thanks, I'm testing.

**Comment by jbonofre** [comment]
I will also test when using `<config/>` in a feature to check if the corresponding `cfg` file is correctly created (as it is on 4.1.x).

**Comment by jbonofre** [comment]
itests module is failing on my box. I'm checking.

**Comment by jbonofre** [comment]
The last commit breaks the itests:

```
org.apache.karaf.itests.JMXSecurityTest.txt:Tests run: 4, Failures: 2, Errors: 0, Skipped: 0, Time elapsed: 6.491 s <<< FAILURE! - in org.apache.karaf.itests.JMXSecurityTest
org.apache.karaf.itests.JMXSecurityTest.txt:testJMXSecurityAsAdmin(org.apache.karaf.itests.JMXSecurityTest)  Time elapsed: 0.291 s  <<< FAILURE!
org.apache.karaf.itests.JMXSecurityTest.txt:testJMXSecurityAsManager(org.apache.karaf.itests.JMXSecurityTest)  Time elapsed: 0.281 s  <<< FAILURE!
org.apache.karaf.itests.ssh.ConfigSshCommandSecurityTest.txt:Tests run: 2, Failures: 2, Errors: 0, Skipped: 0, Time elapsed: 29.836 s <<< FAILURE! - in org.apache.karaf.itests.ssh.ConfigSshCommandSecurityTest
org.apache.karaf.itests.ssh.ConfigSshCommandSecurityTest.txt:testConfigCommandSecurityWithoutEditSessionViaSsh(org.apache.karaf.itests.ssh.ConfigSshCommandSecurityTest)  Time elapsed: 17.022 s  <<< FAILURE!
org.apache.karaf.itests.ssh.ConfigSshCommandSecurityTest.txt:testConfigCommandSecurityViaSsh(org.apache.karaf.itests.ssh.ConfigSshCommandSecurityTest)  Time elapsed: 7.386 s  <<< FAILURE!
```

I gonna take a look.

**Comment by jbonofre** [comment]
Thanks, I'm retesting ...

**Pull request closed without merging**
