### PR TITLE
[KARAF-2925] Add jmxmp support on Karaf JMX service

### PR DESCRIPTION
**Pull request by jbonofre**
This is a work in progress, I have to finalize the security layer and set `jmxmp` optional (`rmi` will remain the default protocol).

### CODE REVIEW

**Comment by mattrpav** [comment]
@jbonofre what are your thoughts on back-porting this to 4.1.x?

**Comment by jbonofre** [comment]
@mattrpav yes, I already have a branch ready with that. I just have to complete the security layer. I will do that tonight or tomorrow.

**Comment by mattrpav** [comment]
@jbonofre awesome, thanks!  Let me know if you could use any help testing, etc.

**Comment by jbonofre** [comment]
Resuming my work on that one.

**Comment by tmoreira2020** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by mattrpav** [comment]
@jbonofre thoughts on this patch? Let me know if I can assist in anyway to get it in 4.2.x. 

It would be super helpful to have JMX available outside the container-local network!

**Comment by jbonofre** [comment]
@mattrpav I will resume my work on this patch (it's almost done).

**Comment by mattrpav** [comment]
@jbonofre any luck on this one? Let me know if i can help. If it helps, I'd say target 4.2.x only.. don't think there is a need to also back-port to 4.1.x

**Pull request merged**
