### PR TITLE
whitespace

### PR DESCRIPTION
**Pull request by gmcdonald**
test PR, so not merge

### CODE REVIEW

**Comment by skitt** [comment]
@gmcdonald you can convert this to a draft, that way it won’t risk being merged ;-). All the checks should still run. On the right-hand-side, in the “Reviewers” section, click on “Still in progress? Convert to draft”.

**Comment by gmcdonald** [comment]
> @gmcdonald you can convert this to a draft, that way it won’t risk being merged ;-). All the checks should still run. On the right-hand-side, in the “Reviewers” section, click on “Still in progress? Convert to draft”.

Now why didnt I think of that!

**Comment by gmcdonald** [comment]
I am wondering if the problem is that this is a Maven type job and cant be used with GH App creds.

Any way you can copy this job into a multibranch or Org Folder type job?

**Comment by jbonofre** [comment]
@gmcdonald we already have a multibranch project on new-builds as well. However, I wanted to avoid to create multibranch/org folder to mimic what we had before on buids.a.o.

**Pull request closed without merging**
