### PR TITLE
[KARAF-5107] Add DeploymentListener

### PR DESCRIPTION
**Pull request by rovarga**
This adds the capability for external components to hook into
the Deployer machinery, so they can perform operations at
opportune moments.

Signed-off-by: Robert Varga <robert.varga@pantheon.tech>

### CODE REVIEW

**Comment by jbonofre** [comment]
R: @jbonofre

**Comment by rovarga** [comment]
I'll fixup the test failures later today

**Comment by jbonofre** [comment]
Thanks, I'm reviewing.

**Comment by jbonofre** [comment]
retest this please

**Comment by jbonofre** [comment]
I'm checking why Jenkins is failing.

**Comment by jbonofre** [comment]
Jenkins failed due to insufficient memory. I'm checking locally.

**Comment by jbonofre** [comment]
`/AssemblyDeployCallback` (in profile) should be updated to reflect the change. You have to add `callListeners()` method there.

Do you want I do it or you do ?

**Comment by rovarga** [comment]
I will have an update in a few minutes, thanks.

**Comment by jbonofre** [comment]
Thanks for the update, I take a look.

**Pull request merged**
