### PR TITLE
[KARAF-5781] Properties edit doesn't conserve the existing ones. (On karaf-4.1.x)

### PR DESCRIPTION
**Pull request by vanSabben**
Now it use the existing file and performs the specified changes.

Signed-off-by: van Sabben <4246302+vanSabben@users.noreply.github.com>

### CODE REVIEW

**Comment by jbonofre** [comment]
Please, it's better to create PR based on master (in order to have Jenkins tests the PR),  then we cherry-pick on target branch when  applicable.
I guess this change can also affect master right ?

**Comment by jbonofre** [comment]
Please, it's better to create PR based on master,  then we cherry-pick on target branch when  applicable.
I guess this change can also affect master right ?

**Comment by jbonofre** [comment]
retest this please

**Comment by vanSabben** [comment]
I did it and tested it. Cherry-pick is possible. It is easier (for you) to use PR. See PR #552 for master.

**Comment by vanSabben** [comment]
retest this please

**Pull request merged**
