### PR TITLE
Fixed image URLs

### PR DESCRIPTION
**Pull request by AndreVirtimo**
Found broken image URLs on https://karaf.apache.org/manual/latest/#_monitoring

I have set the imagesdir attribute in the document. It's also possible to set the URL in the build procees (https://asciidoctor.org/docs/user-manual/#attribute-assignment-precedence).

### CODE REVIEW

**Comment by jbonofre** [comment]
@AndreVirtimo can you please rebase from `master` ?

**Comment by AndreVirtimo** [comment]
@jbonofre I have rebase my master. I'm not sure if this was the right way. Is it now ok?

**Comment by jbonofre** [comment]
You should use `git rebase -i` to squash the commits. But nevermind, I will squash myself.

**Comment by AndreVirtimo** [comment]
Thank you for the tipp.

**Pull request merged**
