### PR TITLE
[KARAF-5164] Use Maven reactor to resolve artifacts needed by VerifyM…

### PR DESCRIPTION
**Pull request by grgrzybek**
…ojo and AssemblyMojo

### CODE REVIEW

**Comment by cschneider** [comment]
R: @cschneider

**Comment by jbonofre** [comment]
CC: @jbonofre

**Comment by jbonofre** [comment]
retest this please

**Comment by cschneider** [comment]
LGTM,  One question @grgrzybek. Currently you allow to optionally add it on top of the normal resolver. Would it be bad to always use the reactor based resolver?

**Comment by grgrzybek** [comment]
@cschneider using reactor resolver only? without delegating to normal? but normal (pax-url-aether) resolver is needed to resolve many other artifacts during feature installation / veriication

**Comment by cschneider** [comment]
I mean using reactor + normal resolver always.

**Comment by jbonofre** [comment]
I think it's better:
1. to have a Jenkins passed before merging
2. Using a merge commit message with "This closes #xxx" to automatically close the PR.

**Comment by cschneider** [comment]
Not so sure about the merge commit message. The way @grgrzybek did the merge the PR goes to status merged. So I think this is fine. We also both gave LGTM so I think it is fine for him to merge.

**Comment by jbonofre** [comment]
@cschneider he has his branch, so he can do a simple `git merge --no-ff -m "This closes #xxx"`

**Pull request merged**
