### PR TITLE
Code cleanups

### PR DESCRIPTION
**Pull request by skitt**
This is mostly automated cleanup; I can split the patch series up if necessary.

### CODE REVIEW

**Comment by jbonofre** [comment]
@skitt do you mind if I squash the commits in one ? It would be easier to me to backport on `karaf-4.2.x` branch.

**Comment by skitt** [comment]
> @skitt do you mind if I squash the commits in one ? It would be easier to me to backport on `karaf-4.2.x` branch.

No problem, in fact I’ve gone ahead and squashed them myself (in the PR, not merged).

**Comment by jbonofre** [comment]
@skitt great, I did the review and tested. It's good for me. I'm merging and cherry pick on `karaf-4.2.x`.

**Comment by jbonofre** [comment]
By the way, I'm doing a test on the cherry pick on `karaf-4.2.x` with JDK8 as it should be compatible. Until Karaf 4.3.0 is not released, I would like to keep 4.2.x as close as possible to 4.3.x (easier to cherry pick).

**Comment by skitt** [comment]
> By the way, I'm doing a test on the cherry pick on `karaf-4.2.x` with JDK8 as it should be compatible. Until Karaf 4.3.0 is not released, I would like to keep 4.2.x as close as possible to 4.3.x (easier to cherry pick).

Yup, there’s nothing requiring JDK > 8 here.

**Pull request merged**
