### PR TITLE
Reintroduce MavenTest itest to test on Jenkins (thanks a PR)

### PR DESCRIPTION
**Pull request by jbonofre**
Reintroduce the MavenTest itest in a PR in order to be able to test on Jenkins (thanks to the karaf-pr job).

### CODE REVIEW

**Comment by jbonofre** [comment]
retest this please

**Comment by jbonofre** [comment]
retest this please

**Comment by jbonofre** [comment]
restest this please

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/karaf-pr/1/

**Comment by jbonofre** [comment]
retest this please

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/karaf-pr/2/

**Comment by jbonofre** [comment]
retest this please

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/karaf-pr/3/

**Comment by jbonofre** [comment]
retest this please

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/karaf-pr/4/

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/karaf-pr/6/

**Comment by jbonofre** [comment]
retest this please

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/karaf-pr/7/

**Comment by jbonofre** [comment]
retest this please

**Pull request merged**
