### PR TITLE
EntrySet should be iterated when both the key and value are needed

### PR DESCRIPTION
**Pull request by apupier**
Signed-off-by: Aurélien Pupier <apupier@redhat.com>

### CODE REVIEW

**Comment by jbonofre** [comment]
R: @jbonofre

**Comment by apupier** [comment]
it brings performance value, it avoids to access and search two times in the map. it is making a visible effect for large Maps but i don't know which ones can be big or not.

Please note that there are a lot more of this in the codebase.

**Comment by jbonofre** [comment]
FYI, the compiler (since Java 1.7 update 40) can already optimize the iteration on the map. Further more, those maps are pretty small ;) Thanks anyway !

**Comment by apupier** [comment]
@jbonofre do you have a reference link for that? i would like to report it to Sonar in order that they don't report it as an issue if source is requiring Java 7

**Comment by jbonofre** [comment]
Let me find it. Anyway, I prefer your approach, it's clearer ;)

**Pull request closed without merging**
