### PR TITLE
[KARAF-5412] Upgrade to ASM 6.0

### PR DESCRIPTION
**Pull request by jbonofre**

### CODE REVIEW

**Comment by gnodet** [comment]
Yeah, that's what jenkins says too ;-)
  https://builds.apache.org/job/karaf-pr/114/console

**Comment by jbonofre** [comment]
It's the first step: I plan to upgrade the dependencies in new commits of this PR.

**Comment by jbonofre** [comment]
Thanks !

**Comment by gnodet** [comment]
Superceded by #404

**Pull request closed without merging**
