### PR TITLE
Karaf 5376 overrides v2

### PR DESCRIPTION
**Pull request by grgrzybek**

### CODE REVIEW

**Comment by grgrzybek** [comment]
Hello. Please do not merge this yet - I'd just like to get some comments from review - if you have some time to spare.

I wrote about the [idea behind this PR to dev@karaf.apache.org](http://karaf.922171.n3.nabble.com/heads-up-long-quot-Features-Processor-quot-that-replaces-overrides-and-blacklisting-and-more-td4052014.html)

**Comment by grgrzybek** [comment]
And please excuse me mixing different JIRAs in single PR - there's no way to have them fixed separately (more JIRAs will come to this, or related PR - mostly related to karaf-maven-plugin)

**Comment by jbonofre** [comment]
retest this please

**Comment by grgrzybek** [comment]
retest this please

**Comment by grgrzybek** [comment]
retest this please

**Comment by grgrzybek** [comment]
closing, to prepare squashed PR

**Pull request closed without merging**
