### PR TITLE
[KARAF-2511] Add examples in the distribution

### PR DESCRIPTION
**Pull request by jbonofre**

### CODE REVIEW

**Comment by jbonofre** [comment]
I gonna rebase and prepare the merge. It would be great to add a JPA examples using Aries JPA with `cfg` file instead of `persistence.xml`.

**Comment by fpapon** [comment]
Agree, +1

**Comment by jbonofre** [comment]
Rebased and cleanup. I'm adding some new examples.

**Comment by jbonofre** [comment]
retest this please

**Comment by jbonofre** [comment]
retest this please

**Pull request merged**
