### PR TITLE
Remove Spring 4.0

### PR DESCRIPTION
**Pull request by skitt**
This is part of KARAF-6722, but doesn’t fix it entirely.

Spring 4.0 is obsolete, no longer maintained upstream.
https://github.com/spring-projects/spring-framework/wiki/Upgrading-to-Spring-Framework-4.x
documents how to upgrade to 4.3, the currently-supported line in the
4.x family.

Signed-off-by: Stephen Kitt <skitt@redhat.com>

### CODE REVIEW

**Comment by skitt** [comment]
This is a breaking change, so probably material for a major release (assuming it’s acceptable).

**Comment by jbonofre** [comment]
@skitt I think it makes sense to include this cleanup for Karaf 4.3.x.

**Comment by skitt** [comment]
retest this please

**Comment by skitt** [comment]
retest this please

**Pull request merged**
