### PR TITLE
KARAF-5124 Fix location logging in Karaf console

### PR DESCRIPTION
**Pull request by clockard**
See https://issues.apache.org/jira/browse/KARAF-5124

### CODE REVIEW

**Comment by clockard** [comment]
@gnodet @cschneider Could you take a look at this pr?

**Comment by jbonofre** [comment]
R: @jbonofre

**Comment by jbonofre** [comment]
Can you please base the pull  request on  master ? We cherry pick on other branches by ourselves.

**Comment by jbonofre** [comment]
I can do it for you if you prefer.

**Comment by clockard** [comment]
Created master pr https://github.com/apache/karaf/pull/303. Closing this one.

**Comment by jbonofre** [comment]
Thanks !

**Pull request closed without merging**
