### PR TITLE
Extend the completion method of shell:source

### PR DESCRIPTION
**Pull request by xipki**

### CODE REVIEW

**Comment by jbonofre** [comment]
retest this please

**Comment by xipki** [comment]
Testing with 'mvn clean install' with following result:
....
[INFO] Apache Karaf :: Archetypes :: Bundle Archetype ..... SUCCESS [  5.034 s]
[INFO] Apache Karaf :: Archetypes :: Blueprint Archetype .. SUCCESS [  5.212 s]
[INFO] Apache Karaf :: Integration Tests .................. SUCCESS [31:39 min]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 41:26 min
[INFO] Finished at: 2018-05-12T19:03:18+02:00
[INFO] Final Memory: 177M/954M
[INFO] ------------------------------------------------------------------------

**Comment by jbonofre** [comment]
The "retest this please" is not for you: it's the key sentence to trigger a build on Jenkins (it failed on previous run).

**Comment by jbonofre** [comment]
retest this please

**Comment by jbonofre** [comment]
retest this please

**Pull request merged**
