### PR TITLE
[KARAF-5729] Improve usage of awk on Solaris + delete blank space in …

### PR DESCRIPTION
**Pull request by oscerd**
…sed command causing Karaf startup to fail on Solaris and AIX

### CODE REVIEW

**Comment by oscerd** [comment]
@StephaneRicci I opened a Pull Request starting from your branch if you don't mind, after I read your comment.

**Comment by oscerd** [comment]
Did you test this also with new version of Java (9, 10 or early 11)?

**Comment by jbonofre** [comment]
It doesn't look fully correct to me. I'm doing a complete review.

**Comment by oscerd** [comment]
yeah, I opened the PR to check with the CI job first

**Comment by baptistedaroit** [comment]
As requested in the [KARAF-5729](https://issues.apache.org/jira/projects/KARAF/issues/KARAF-5729?filter=allopenissues), this PR aims to fix the following errors when starting Karaf on Solaris and AIX:
```
sed: command garbled: s/_.*//g; s/^1\.//g ; s/\..*//g;
awk: can't open /version/ {print $2}
```

The associated code has been tested on the environments below.

Solaris SPARC v9 with both JDK 8, 9 & 10:
- Java(TM) SE Runtime Environment 18.3 (build 10.0.1+10)
- Java(TM) SE Runtime Environment (build 9.0.4+11)
- Java(TM) SE Runtime Environment (build 1.8.0_141-b15) 

AIX 7.1 TL4 with IBM J9 JDK 8:
- IBM J9 VM (build 2.9, JRE 1.8.0 AIX ppc-32 20180208_378436)

**Comment by oscerd** [comment]
It would be good to test it on HP-UX. Lets wait for @jbonofre review

**Comment by baptistedaroit** [comment]
I have opened another PR (as this is about another issue) that allow to start karaf properly on HP-UX - Please see [KARAF-5753](https://github.com/apache/karaf/pull/504)

**Comment by oscerd** [comment]
Thanks for the details. Lets wait for JB.

**Comment by jbonofre** [comment]
Can you please rebase and fix conflicts ? Thanks.

**Comment by jbonofre** [comment]
Thanks, I'm resuming the review.

**Comment by baptistedaroit** [comment]
Okay, Thanks.

**Comment by oscerd** [comment]
Maybe the PR should be cleaned a bit.. It's difficult to understand what is the real update here...

**Comment by oscerd** [comment]
@baptistedaroit thanks a lot :-)

**Comment by jbonofre** [comment]
@baptistedaroit thx, resuming review.

**Pull request merged**
