### PR TITLE
Fix bug when display help in eclipse debuger

### PR DESCRIPTION
**Pull request by sginer**

### CODE REVIEW

**Comment by jbonofre** [comment]
retest this please

**Comment by sginer** [comment]
Sorry, but I dont understand your comment
You want me to test the modification in my environnement ? All tests on shell project are fine on my environnement.

**Comment by oscerd** [comment]
It's a message for the CI server to run the tests again on the Apache CI server.

**Comment by jbonofre** [comment]
@sginer no ;) the key words `retest this please` trigger a build on Jenkins ;)
Anyway, the build is failing on `master`. I'm thinking it now, you will just have to rebase when done.

**Comment by jbonofre** [comment]
Can you please rebase ? I fixed the build on `master` with #606

**Pull request merged**
