### PR TITLE
[KARAF-5528] Stop refreshed bundles together with updated and deleted…

### PR DESCRIPTION
**Pull request by grgrzybek**
… ones

This time with `if (!noRefresh)`

### CODE REVIEW

**Comment by jbonofre** [comment]
retest this please

**Comment by grgrzybek** [comment]
retest this please

**Comment by grgrzybek** [comment]
retest this please

**Comment by grgrzybek** [comment]
@jbonofre @gnodet I had problem with this issue - stopping bundles that are in `toRefresh` earlier - together with the ones being updated caused pax-logging-log4j2 bundle to be stopped earlier because it's optionally wired to `org.fusesource.jansi` which is installed with `shell` feature. And we loose logging output earlier.

I suggest adding jansi to `etc/startup.properties` (`framework` feature) - wdyt?

**Pull request merged**
