### PR TITLE
Update jaxb export versions

### PR DESCRIPTION
**Pull request by rovarga**
Java 8 shipped version 2.2.8
Java 9 shipped version 2.3.0

Signed-off-by: Robert Varga <nite@hq.sk>

### CODE REVIEW

**Comment by rovarga** [comment]
@jbonofre looks like CI is running out of space, would this be a fair target for 4.1.x backport?

**Comment by jbonofre** [comment]
@rovarga agree for the backport, I will tackle that.

**Comment by jbonofre** [comment]
retest this please

**Comment by jbonofre** [comment]
retest this please

**Comment by jbonofre** [comment]
retest this please

**Comment by jbonofre** [comment]
retest this please

**Comment by jbonofre** [comment]
retest this please

**Pull request merged**
