### PR TITLE
[KARAF-7423] Add logback configuration option

### PR DESCRIPTION
**Pull request by i-thiemann**
I've added an xml based configuration service implementation for logback configurations and corresponding unittests and documentation.

### CODE REVIEW

**Comment by i-thiemann** [comment]
> Are we sure we want logback by default ? I would rather prefer to keep log4j2 style by default, and document how to have logback instead. Or eventually create another framework/static feature (with logback classifier for instance) to easily use logback.
> 
> Thoughts ?

The default option is still log4j2. The logback service just also exists now and can be included if needed.

**Comment by i-thiemann** [comment]
I understand the confusion. I made a mistake in including pax-logging-logback in the wrong place in assembly I'll remove it and update my pull request

**Comment by i-thiemann** [comment]
retest this please

**Comment by jbonofre** [comment]
If you don't mind, I will squash the 5 commits in a single one.

**Comment by i-thiemann** [comment]
> If you don't mind, I will squash the 5 commits in a single one.

That would be fine.

**Pull request closed without merging**
