### PR TITLE
[KARAF-6410] FeatureProcessor selects wrong override bundle.

### PR DESCRIPTION
**Pull request by hema-1046**

### CODE REVIEW

**Comment by jbonofre** [comment]
Please, can you base the PR on `master` ? I cherry-pick on `karaf-4.2.x` branch once it's done on `master`. Thanks !

**Comment by jbonofre** [comment]
@hema-1046 thx, I'm reviewing.

**Comment by jbonofre** [comment]
retest this please

**Comment by hema-1046** [comment]
retested and works as expected

**Comment by fpapon** [comment]
@hema-1046 the sentence "retest this please"  is for Jenkins automation build ;)

**Comment by hema-1046** [comment]
:D nothing tops good manual work
@fpapon thank you

**Pull request merged**
