### PR TITLE
[KARAF-5919] Be able to store Http Proxy list in order to keep configuration after restart

### PR DESCRIPTION
**Pull request by sjhiggs**

### CODE REVIEW

**Comment by jbonofre** [comment]
I will merge as soon as Jenkins is happy.

**Comment by sjhiggs** [comment]
Looks like Jenkins isn't happy, but I don't think it's related to the commit.  Please let me know if otherwise.

**Comment by jbonofre** [comment]
@sjhiggs it's not related to your changes, it's a flaky test that I will fix.

**Comment by jbonofre** [comment]
retest this please

**Pull request merged**
