### PR TITLE
 Updated Col used by ShellTable. Added support for changing color of a specific cell in a column based on the cell content.

### PR DESCRIPTION
**Pull request by labero**

### CODE REVIEW

**Comment by labero** [comment]
Seems to be fixed now. To be honest, I had some problem finding the error message from the javadoc generation.

**Comment by labero** [comment]
I realized that karaf 4.2 is not supporting lower java versions that 8. So I rebased, squashed some commits, removed the IColorProvider interface and replaced it with the standard "Function" interface from java 8.

However, the Jenkins failure (JMXSecurityTest). I can't see how that is affected by my changes. Is there anything I can do to resolve it?

**Comment by jbonofre** [comment]
The build issue is not related, it's a flaky test that I will fix.

**Comment by jbonofre** [comment]
retest this please

**Pull request merged**
