### PR TITLE
Update karaf-maven-plugin.adoc

### PR DESCRIPTION
**Pull request by thuri**
additional documentation of the switches for zip or tar.gz creation respectively

### CODE REVIEW

**Comment by cschneider** [comment]
Thanks for the contribution .. I will merge it

**Comment by cschneider** [comment]
I merged the PR .. can you close it?

**Comment by thuri** [comment]
of course. Thanks

**Comment by jbonofre** [comment]
@cschneider please, next time, use the clean merge process (that automatically close the PR). Thanks !

**Pull request closed without merging**
