### PR TITLE
Optimize GenerateDescriptorMojo

### PR DESCRIPTION
**Pull request by rovarga**
OpenDaylight typically processes deeply nested feature.xmls, which takes significant time. This PR optimizes GenerateDescriptorMojo, reducing build time observed by a factor of 3.

### CODE REVIEW

**Comment by cschneider** [comment]
R: cschneider

**Comment by cschneider** [comment]
Can you create the PR against master? We only merge to master and then backport.

**Comment by cschneider** [comment]
Apart from that the PR looks good.

**Comment by rovarga** [comment]
@cschneider Thanks for your review, rebased on top of current master.

**Comment by cschneider** [comment]
I also backported to the karaf 4.1.x branch now

**Pull request merged**
