### PR TITLE
KARAF-5300 FeaturesService should use more specific classes for internal model

### PR DESCRIPTION
**Pull request by cschneider**

### CODE REVIEW

**Comment by jbonofre** [comment]
R: @jbonofre

**Comment by jbonofre** [comment]
retest this please

**Comment by cschneider** [comment]
@gnodet Hi Guillaume. Can you also review this PR?

**Comment by cschneider** [comment]
I will keep this PR open for two more days and then merge if there are no other comments.

**Comment by cschneider** [comment]
retest this

**Comment by cschneider** [comment]
retest this please

**Comment by cschneider** [comment]
restest this please

**Pull request merged**
