### PR TITLE
Master maven commands

### PR DESCRIPTION
**Pull request by grgrzybek**

### CODE REVIEW

**Comment by grgrzybek** [comment]
@gnodet @jbonofre @cschneider please review if you like

None of your `~/.m2/settings.xml` or `~/.m2/settings-security.xml` will break

**Comment by jbonofre** [comment]
R: @jbonofre

**Comment by grgrzybek** [comment]
ah - this new bundle isn't installed by default and there's no feature for it (yet). You have to install it manually: `install -s mvn:org.apache.karaf.maven/org.apache.karaf.maven.core/4.2.0-SNAPSHOT`

**Comment by jbonofre** [comment]
I suggest to add a "maven" feature for convenience.

**Pull request closed without merging**
