### PR TITLE
Improve feature construction in karaf-maven-plugin

### PR DESCRIPTION
**Pull request by skitt**
This adds the following features when processing a Maven project to
produce a feature:
* features the project depends on are processed first, so their
  dependencies can be taken into account;
* transitively-depended-on features are loaded;
* bundles are only added if the included features don't already
  include them;
* when not aggregating, features are added to the repositories
  (de-duplicated) [KARAF-1583].

Signed-off-by: Stephen Kitt <skitt@redhat.com>

### CODE REVIEW

**Comment by skitt** [comment]
I'm not too sure of the use of org.eclipse.aether.artifact.DefaultArtifact — but I couldn't figure out another way of converting a repository to a Maven artifact...

**Comment by skitt** [comment]
If this patch is OK, I'll gladly forward-port it to Karaf 4.

**Comment by vorburger** [comment]
This would great to have! It would much simplify features in http://opendaylight.org.

@gnodet and/or @ffang (hi RH), is this something you could have a look at, and possibly merge?

If NOK, can you guide what process or changes would be needed to get this in? Tx!

**Comment by skitt** [comment]
The repository handling is currently sub-optimal when aggregating features, I'll push an updated patch soon.

**Comment by jbonofre** [comment]
R: @jbonofre

**Comment by jbonofre** [comment]
It would be great to create a Jira to track it. Thanks.

**Comment by skitt** [comment]
I'm going to rework this to take into account recent updates to Karaf and to split the fixes up to target specific bugs...

**Comment by jbonofre** [comment]
Thanks, I will review and merge asap.

**Comment by skitt** [comment]
Most of this has actually already been merged to master and back-ported. https://github.com/apache/karaf/pull/228 contains the missing repository features. The rest is a bit more controversial, I'll file a bug about it anyway...

**Comment by jbonofre** [comment]
Let me close this PR (and integrate #228).

**Comment by skitt** [comment]
No problem, in fact I'll close it myself ;-).

**Comment by jbonofre** [comment]
Oh, ok, go ahead ;)

**Pull request closed without merging**
