### PR TITLE
KARAF-7155 - Deleting a factory configuration doesn't delete the associated json file

### PR DESCRIPTION
**Pull request by jassuncao**
JsonConfigInstaller keeps tracks of configurations that are associated
to a json file. When the configuration is deleted it will try to delete
the file.

### CODE REVIEW

**Comment by jbonofre** [comment]
@jassuncao what about using `felix.fileinstall.filename` to delete the file ? This way we don't have to store the factory/pid in the map, just read the `felix.fileinstall.filename` from the properties and remove it.
It's the fix I did.
Thoughts ?

**Comment by jassuncao** [comment]
@jbonofre I had the idea configuration properties wouldn't be available after receiving a ConfigurationEvent.CM_DELETED. I'm almost sure I attempted that, but I might have missed something,

**Comment by jbonofre** [comment]
@jassuncao thanks, let me try something and I will let you know.

**Comment by jbonofre** [comment]
Actually, it works for me.

**Pull request closed without merging**
