### PR TITLE
[KARAF-5649] Add a feature for the manual

### PR DESCRIPTION
**Pull request by fpapon**
Adding a documentation feature in order to published the generated manual in html with the http service.

### CODE REVIEW

**Comment by jbonofre** [comment]
The `documentation` feature doesn't validate, it's because the `manual` module is built only with the `release` profile.

**Comment by jbonofre** [comment]
retest this please

**Comment by jbonofre** [comment]
retest this please

**Comment by jbonofre** [comment]
As the `manual` profile is defined after the `assemby`, the error is "expected".

I propose the following:

1. Remove the `manual` profile in the main `pom.xml`
2. Include `manual` module in the main `pom.xml` (reactor) before the `assembly`

It means the manual will be systematically built, which is not bad IMHO. Especially, the PDF generation is isolated in a dedicated profile.

**Comment by fpapon** [comment]
I removed the manual profile from pom parent and include the manual module in the reactor.

Ready for the review ;)

**Pull request merged**
