### PR TITLE
Refactoring AssemblyMojo

### PR DESCRIPTION
**Pull request by kemitix**
`AssemblyMojo` is a 580 line file with a single 257-line method accounting for the bulk of it. It also has no unit tests.

This creates system tests for `AssemblyMojo` and refactors it into a more manageable structure, all within a new `assembly` package, with suitable unit tests. Code coverage is 100% from either the system tests or the unit tests.

### CODE REVIEW

**Comment by cschneider** [comment]
I will review the changes. Can you fix the conflicts?

**Comment by kemitix** [comment]
On it.

**Comment by kemitix** [comment]
Done. :)

**Comment by cschneider** [comment]
Thanks.

I have looked into the code. I think the big benefit it provides is improved testing of AssemblyMojo.

I do not like the refactoring of AssemblyMojo itself too much. It increases the number of classes a lot and even the number of lines in AssemblyMojo. 

I did some statistics with cloc:
master (sources without tests):
Java                            27            804           1291           5153
AssemblyMojo.java
Java                             1             63            129            388

assembly-mojo-refactoring-4.2.x (sources without tests):
Java                            39            972           1497           5472
AssemblyMojo.java
Java                             1            131            118            430

I think AssemblyMojo needs some refactoring but we should do it less extensively. 

You also changed some other stuff like removing the DependencyHelper30 which I think is a good idea. 
I guess it was simply needed after the dependency upgrades but it is a good change in itself.

So I would like to check if we can salvage parts of your work while not applying all.
I experimented a bit with picking the AssemblyMojoSystemTest from your code and everything it needs to work. I pushed what I have now to 
https://github.com/cschneider/karaf/tree/assembly-mojo-tests/tooling/karaf-maven-plugin

I got most of the tests working 2 errors and 4 failures remain. 

So if you are interested to work on this I propose the following:
1. In one PR provide an update to the poms and removal of the DependencyHelper30 mechanism. 
2. In a second PR provide a fully working implementation of the AssemblyMojoSystemTest (like I started with) while doing only minimal changes in production code.

Then from this base we can discuss how to improve AssemblyMojo.

**Comment by kemitix** [comment]
Okay.

I can do that. I won't be able to get back to this for a few days though.

**Comment by grgrzybek** [comment]
@cschneider @kemitix if #314 is merged, can we close this one? I'm working on new issue I created ([Clean up AssemblyMojo](https://issues.apache.org/jira/browse/KARAF-5468) - related to [Processor mechanism for feature definitions (a.k.a. "better overrides")](https://issues.apache.org/jira/browse/KARAF-5376)), so there'll be a bit more refactoring soon

**Comment by asfgit** [comment]
FAILURE
 
--none--

**Comment by kemitix** [comment]
@grgrzybek Guess I never did get back to this. Closing it to clear the way.

**Comment by grgrzybek** [comment]
Thanks @kemitix for response. I even tried squashing your commits to single one and verify if it's still possible to merge. Your refactoring is impressive, but there were many conflicts, as AssemblyMojo changed since your PR.

I started KARAF-5468 and focused on adding documentation, additional logging and making it consistent with Builder, profiles and features processing. I'm working on it while having your branch opened for inspiration ;)

**Pull request closed without merging**
