### PR TITLE
Cleanup

### PR DESCRIPTION
**Pull request by skitt**
This patch series groups a number of largely mechanical clean-ups.

### CODE REVIEW

**Comment by skitt** [comment]
@jbonofre do you want me to file an issue for these?

**Comment by jbonofre** [comment]
@skitt no need of a Jira.

If you don't mind, I'm doing the review and then I will squash in one commit. Agree ?

**Comment by skitt** [comment]
> If you don't mind, I'm doing the review and then I will squash in one commit. Agree ?

Yup, that’s fine. I pushed the individual commits so that each change would be easily identifiable and reviewable, but it would create a lot of noise in the history!

**Comment by jbonofre** [comment]
retest this please

**Pull request merged**
