### PR TITLE
Update poms and remove DependencyHelper30

### PR DESCRIPTION
**Pull request by kemitix**
@cschneider - picking up from notes on PR #299 

* Enable JaCoCo coverage reporting in `karaf-maven-plugin`, with limit disabled - will not break build
* Define maven version as a property
* Upgrade maven to 3.5.0
* Remove `DependencyHelper30` (remove legacy maven 3.0.x support)
* Upgrade `plexus-utils` to 3.0.24

### CODE REVIEW

**Comment by kemitix** [comment]
retest this please

**Comment by jbonofre** [comment]
R: @jbonofre

**Comment by cschneider** [comment]
@jbonofre Are you working on this?

**Comment by cschneider** [comment]
R: @cschneider

**Pull request merged**
