### PR TITLE
rewrite the CicularBuffer to reduce logservice overhead

### PR DESCRIPTION
**Pull request by rmannibucau**

### CODE REVIEW

**Review by jbonofre — APPROVED** [review]

**Comment by wborn** [comment]
I just did some testing with Karaf 4.2.10 and it seems that that `log:tail` command now often does not show any history. Also if you specific the number of lines e.g. with `log:tail -n 10` it doesn't show logging. Only if I increase the count to a high number e.g. `log:tail -n 1000` it shows logging. Perhaps it's caused by this change. I tested using the [apache-karaf-4.2.10.tar.gz](http://www.apache.org/dyn/closer.lua/karaf/4.2.10/apache-karaf-4.2.10.tar.gz). It does seem to work as expected with Karaf 4.2.9.

**Comment by jbonofre** [comment]
Thanks, I'm reverting the change then for investigation (I didn't see the issue).

**Comment by rmannibucau** [comment]
@wborn can you test https://github.com/apache/karaf/pull/1221 please ?

**Comment by wborn** [comment]
I gave the fix a test on the 4.2.x branch and it seems to work well again! :+1:
A minor issue is that the line count doesn't match the parameter:

```
karaf@root()> log:tail -n 1
18:24:01.071 INFO [CM Configuration Updater (Update: pid=org.ops4j.pax.logging)] Sending Event Admin notification (configuration successful) to org/ops4j/pax/logging/Configuration
18:24:11.917 INFO [CM Configuration Updater (Update: pid=org.ops4j.pax.logging)] Sending Event Admin notification (configuration successful) to org/ops4j/pax/logging/Configuration
^C~                                                                               
karaf@root()> log:tail -n 2
18:24:11.917 INFO [CM Configuration Updater (Update: pid=org.ops4j.pax.logging)] Sending Event Admin notification (configuration successful) to org/ops4j/pax/logging/Configuration
18:24:12.936 INFO [CM Configuration Updater (Update: pid=org.ops4j.pax.logging)] Sending Event Admin notification (configuration successful) to org/ops4j/pax/logging/Configuration
18:24:15.769 INFO [CM Configuration Updater (Update: pid=org.ops4j.pax.logging)] Sending Event Admin notification (configuration successful) to org/ops4j/pax/logging/Configuration
```

**Comment by jbonofre** [comment]
I will do the quick fix for line count. Thanks !

**Pull request merged**
