### PR TITLE
[KARAF-6674] Upgrade to Awaitility 4.0.2

### PR DESCRIPTION
**Pull request by skitt**
Release notes:
https://github.com/awaitility/awaitility/wiki/ReleaseNotes40
Changelog:
https://raw.githubusercontent.com/awaitility/awaitility/master/changelog.txt

None of the backwards-incompatible changes in 4.0 affect Karaf.

Signed-off-by: Stephen Kitt <skitt@redhat.com>

### CODE REVIEW

**Comment by jbonofre** [comment]
Did you test locally, especially itests with pax-exam ? I already start the update process but it would need to be updated in pax exam afair.

**Comment by jbonofre** [comment]
retest this please

**Comment by skitt** [comment]
> Did you test locally, especially itests with pax-exam ? I already start the update process but it would need to be updated in pax exam afair.

I’d run the unit tests but not the integration tests, and this does indeed require a Pax Exam update:

```
org.apache.felix.resolver.reason.ReasonException: Unable to resolve root: missing requirement [root] osgi.identity; osgi.identity=test-dependencies; type=karaf.feature; version="[0,0.0.0]"; filter:="(&(osgi.identity=test-dependencies)(type=karaf.feature)(version>=0.0.0)(version<=0.0.0))" [caused by: Unable to resolve test-dependencies/0.0.0: missing requirement [test-dependencies/0.0.0] osgi.identity; osgi.identity=org.awaitility; type=osgi.bundle; version="[4.0.2,4.0.2]"; resolution:=mandatory [caused by: Unable to resolve org.awaitility/4.0.2: missing requirement [org.awaitility/4.0.2] osgi.wiring.package; filter:="(&(osgi.wiring.package=org.hamcrest)(version>=2.1.0)(!(version>=3.0.0)))"]]
```

**Comment by skitt** [comment]
> I’d run the unit tests but not the integration tests, and this does indeed require a Pax Exam update:
> 
> ```
> org.apache.felix.resolver.reason.ReasonException: Unable to resolve root: missing requirement [root] osgi.identity; osgi.identity=test-dependencies; type=karaf.feature; version="[0,0.0.0]"; filter:="(&(osgi.identity=test-dependencies)(type=karaf.feature)(version>=0.0.0)(version<=0.0.0))" [caused by: Unable to resolve test-dependencies/0.0.0: missing requirement [test-dependencies/0.0.0] osgi.identity; osgi.identity=org.awaitility; type=osgi.bundle; version="[4.0.2,4.0.2]"; resolution:=mandatory [caused by: Unable to resolve org.awaitility/4.0.2: missing requirement [org.awaitility/4.0.2] osgi.wiring.package; filter:="(&(osgi.wiring.package=org.hamcrest)(version>=2.1.0)(!(version>=3.0.0)))"]]
> ```

Or rather, a Hamcrest ServiceMix bundle update?

**Comment by skitt** [comment]
OK, a Hamcrest upgrade is required, and the ServiceMix bundle is no longer needed. See the updated commit.

**Comment by skitt** [comment]
... and Pax pulls in Tipi Hamcrest so that needs fixing too.

**Comment by jbonofre** [comment]
Yeah. I already start the update. Please next time ping me before starting an upgrade. Sometime it is not just changing the Pom ;)

**Comment by skitt** [comment]
> Yeah. I already start the update. Please next time ping me before starting an upgrade. Sometime it is not just changing the Pom ;)

Indeed, I’ve been tripped up before by upgrades involving Pax!

**Pull request closed without merging**
