### PR TITLE
KARAF-4569: OSGi framework is not shut-down gracefully on SIGTERM

### PR DESCRIPTION
**Pull request by lburgazzoli**

### CODE REVIEW

**Comment by CodingFabian** [comment]
wouldn't a shutdown hook accomplish the same?

**Comment by lburgazzoli** [comment]
Shutdown Hook was my first attempt, but it turned out not to be the same maybe because of the ordering (i.e. the framework may have installed one on its own)

**Comment by jbonofre** [comment]
R: @jbonofre

**Comment by lburgazzoli** [comment]
@jbonofre any finding I should fix ?

**Comment by jbonofre** [comment]
Merging

**Pull request merged**
