### PR TITLE
Use Felix HTTP (Jetty) by default (instead of Pax Web)

### PR DESCRIPTION
**Pull request by jbonofre**

### CODE REVIEW

**Review by fpapon — APPROVED** [review]
LGTM

**Review by oscerd — APPROVED** [review]

**Review by skitt — APPROVED** [review]

**Comment by jbonofre** [comment]
I have some features to fix (spring-security and others). I'm updating the PR with the fixes.

**Comment by skitt** [comment]
> I have some features to fix (spring-security and others). I'm updating the PR with the fixes.

On a similar topic, #1128, #1129, and #1130 are still pending ;-).

**Comment by jbonofre** [comment]
@skitt it's on the way for Spring features cleanup.

**Comment by jbonofre** [comment]
I still need some fixes on examples.

**Comment by jbonofre** [comment]
Rethinking about that, I think I found a better move: I will keep Pax Web by default on Karaf 4.3.x, but upgrading to 7.3.x. Even it's not 100% R7 compliant, it already covers 95% of the spec. So, instead of holding Karaf 4.3.x for too long, I will move this way.

**Pull request closed without merging**
