### PR TITLE
[KARAF-6156] Update JaasHelper to support extending Karaf JAAS (4.1.x)

### PR DESCRIPTION
**Pull request by mattrpav**
Use an .isAssignableFrom() instead of class name string comparison. This allows for extending Karaf JAAS [User,Group,Role]Principal classes

### CODE REVIEW

**Comment by jbonofre** [comment]
Please, just open PR based on `master`. The automatic Jenkins job is based on `master`. Thanks anyway ;)

**Comment by mattrpav** [comment]
Do you no longer want to receive back-ported PRs?

**Comment by jbonofre** [comment]
It's up to you, I just mean that the build could fail on Jenkins as Jenkins PR build is only based on master.

**Comment by jbonofre** [comment]
retest this please

**Comment by mattrpav** [comment]
> It's up to you, I just mean that the build could fail on Jenkins as Jenkins PR build is only based on master.

Its easy enough for me to make back-ported PRs.. if you don't mind the build break noise, I'll keep them coming as long as they are helpful.  Won't hurt my feelings either way.

**Pull request closed without merging**
