### PR TITLE
[KARAF-3278] Display warning message when trying to install an alread…

### PR DESCRIPTION
**Pull request by oscerd**
…y installed bundle

Hi all,

This PR is related to:
https://issues.apache.org/jira/browse/KARAF-3278

Andrea

### CODE REVIEW

**Comment by jbonofre** [comment]
You define this at bundle level, the purpose is more at feature level.

The purpose is to have a warning when you do feature:install on an already installed feature.

Can you update the PR accordingly ?

**Comment by oscerd** [comment]
Yes, for sure! Do I have to remove the control at bundle level? Or I can
leave the control at bundle level and add another control at feature level?
Il 24/nov/2015 21:26, "Jean-Baptiste Onofré" <notifications@github.com> ha
scritto:

**Comment by jbonofre** [comment]
I don't think it's good for bundle, as it can trigger an update. So I would keep it only for feature.

**Comment by oscerd** [comment]
OK! I'll change accordingly :-)
Il 24/nov/2015 21:33, "Jean-Baptiste Onofré" <notifications@github.com> ha
scritto:

**Comment by oscerd** [comment]
PR updated

**Pull request merged**
